src-test/org/etools/j1939_84/modules/DTCModuleTest.java, src/org/etools/j1939_84/modules/DTCModule.java
Update DTCModule/DTCModuleTest for the DM23 messaging and to conform to the new RequestResult pattern and add the destination specific request.  Fix #113
=> Update DTCModule/DTCModuleTest for DM23 

src-test/org/etools/j1939_84/modules/DTCModuleTest.java, src/org/etools/j1939_84/modules/DTCModule.java
Fix #115 Add DM28 destination specific call and update the global cal to conform to the RequestResult pattern.
=> Update DTCModule/DTCModule to add DM28 

src-test/org/etools/j1939_84/modules/DTCModuleTest.java, src/org/etools/j1939_84/bus/j1939/packets/DM25ExpandedFreezeFrame.java, src/org/etools/j1939_84/modules/DTCModule.java
Fix #79 Update DM25 to conform to new RequestResults object and combine/clean up duplicated code.
=> Update DTCModule/DTCModuleTest for DM25 messaging

src-test/org/etools/j1939_84/bus/j1939/packets/DM29DtcCountsTest.java, src-test/org/etools/j1939_84/modules/DTCModuleTest.java, src/org/etools/j1939_84/bus/j1939/packets/DM29DtcCounts.java
Fix #78 Update DTCModuleTest to add testing for DM29s.  Also, fixed the toString() method in the DM29 object and update its test.
=> Update DTCModuleTest for DM29

src-test/org/etools/j1939_84/bus/j1939/packets/DM6PendingEmissionDTCPacketTest.java, src-test/org/etools/j1939_84/bus/j1939/packets/DiagnosticTroubleCodePacketTest.java, src-test/org/etools/j1939_84/modules/DTCModuleTest.java, src/org/etools/j1939_84/bus/j1939/packets/DiagnosticTroubleCodePacket.java
Fix #192 Update the toString method of DiagnosticTroubleCodePacket to print "No DTCs" on the same line as the packet.  All affected unit tests were updated as well.
=> Update DiagnosticTroubleCodePacket toString() formatting

src-test/org/etools/j1939_84/bus/j1939/packets/LampStatusTest.java, src/org/etools/j1939_84/bus/j1939/packets/LampStatus.java
Fix #195 add two additional  states of "alternate off" and "not supported" to implement Section A.8 from the requirements.
=> Add additional LampStatuses

src-test/org/etools/j1939_84/bus/j1939/packets/DTCLampStatusTest.java, src/org/etools/j1939_84/bus/j1939/packets/DTCLampStatus.java
Fix #197 update the DTCLampStatus to correctly parse lamp statuses and write additional tests.
=> Update DTCLampStatus to parse lamp statuses correctly

src-test/org/etools/j1939_84/bus/j1939/packets/DiagnosticTroubleCodeTest.java, src/org/etools/j1939_84/bus/j1939/packets/DiagnosticTroubleCode.java
Fix #199 Add equals and hashcode override methods to DiagnosticTroubleCode class and the associated testing to the DiagnosticTroubleCodeTest.
=> Add equals and hashcode override methods to DiagnosticTroubleCode

src-test/org/etools/j1939_84/modules/DTCModuleTest.java
Fix #195 add two additional  states of "alternate off" and "not supported" to implement Section A.8 from the requirements.
=> Fix DTCModuleTest to account for newly added states

src-test/org/etools/j1939_84/modules/DTCModuleTest.java, src/org/etools/j1939_84/modules/DTCModule.java
Fix #194 Add readDM1() method to DTCModule and its associated unit tests to DTCModuleTest.
=> Read DM1s off the bus

src-test/org/etools/j1939_84/bus/j1939/packets/DM28PermanentEmissionDTCPacketTest.java, src-test/org/etools/j1939_84/bus/j1939/packets/DM31ScaledTestResultTest.java, src-test/org/etools/j1939_84/bus/j1939/packets/DM6PendingEmissionDTCPacketTest.java, src-test/org/etools/j1939_84/bus/j1939/packets/DiagnosticTroubleCodePacketTest.java
Fix #195 add two additional  states of "alternate off" and "not supported" to implement Section A.8 from the requirements.
=> Correct tests to use correct lamp states in the packets values

src-test/org/etools/j1939_84/modules/DTCModuleTest.java, src/org/etools/j1939_84/modules/DTCModule.java
Fix #229 Update the DTCModule and DTCModuleTest to handle the DM27 requests for DS and global calls.
=> Update DTCModule for DM27 messaging

src-test/org/etools/j1939_84/controllers/part1/Step13ControllerTest.java, src/org/etools/j1939_84/controllers/part1/Step13Controller.java
Fix #449 Update the verbiage per client feedback on the reporting as well as fix incorrect logic when computing the differences between packets.
=> Fix Part01Step13 logic and verbiage

src-test/org/etools/j1939_84/controllers/part1/Step11ControllerTest.java, src-test/org/etools/j1939_84/controllers/part1/Step13ControllerTest.java, src-test/org/etools/j1939_84/controllers/part1/Step14ControllerTest.java, src-test/org/etools/j1939_84/controllers/part1/Step16ControllerTest.java, src-test/org/etools/j1939_84/controllers/part1/Step17ControllerTest.java, src-test/org/etools/j1939_84/controllers/part1/Step18ControllerTest.java, src-test/org/etools/j1939_84/controllers/part1/Step19ControllerTest.java, src-test/org/etools/j1939_84/controllers/part1/Step20ControllerTest.java, src-test/org/etools/j1939_84/controllers/part1/Step21ControllerTest.java, src-test/org/etools/j1939_84/controllers/part1/Step22ControllerTest.java, src-test/org/etools/j1939_84/controllers/part1/Step23ControllerTest.java, src-test/org/etools/j1939_84/controllers/part1/Step24ControllerTest.java, src/org/etools/j1939_84/controllers/StepController.java, src/org/etools/j1939_84/controllers/part1/Step07Controller.java, src/org/etools/j1939_84/controllers/part1/Step11Controller.java, src/org/etools/j1939_84/controllers/part1/Step13Controller.java, src/org/etools/j1939_84/controllers/part1/Step14Controller.java, src/org/etools/j1939_84/controllers/part1/Step16Controller.java, src/org/etools/j1939_84/controllers/part1/Step17Controller.java, src/org/etools/j1939_84/controllers/part1/Step18Controller.java, src/org/etools/j1939_84/controllers/part1/Step19Controller.java, src/org/etools/j1939_84/controllers/part1/Step20Controller.java, src/org/etools/j1939_84/controllers/part1/Step21Controller.java, src/org/etools/j1939_84/controllers/part1/Step22Controller.java, src/org/etools/j1939_84/controllers/part1/Step23Controller.java, src/org/etools/j1939_84/controllers/part1/Step24Controller.java
Centralize the check for Missing NACKs and differences between Global and DS Responses in the StepController.  Then fixed all the tests.
=> Fix #426 Various Part1 Steps Report Global and DS Response differences inaccurately

src-test/org/etools/j1939_84/controllers/part1/Part01Step13ControllerTest.java, src/org/etools/j1939_84/controllers/part1/Part01Step13Controller.java
If 255 is received from Active Code Counts or Previously Active Code Counts ignore the values.
=> Fix #478 - Part 1 Step 13 should allow NA for code counts

src-test/org/etools/j1939_84/controllers/part1/Part01Step10ControllerTest.java, src/org/etools/j1939_84/bus/j1939/J1939.java, src/org/etools/j1939_84/controllers/StepController.java, src/org/etools/j1939_84/controllers/part1/Part01Step10Controller.java, src/org/etools/j1939_84/modules/DTCModule.java
Added `requestDM11()` method to `J1939` class which will request DM11 and return AckPackets. This allows the method to then call `globalRequestOnce()` which will not retry the request.
=> Fix #498 6.1.10 DM11 should not have retries

README.md, src-test/org/etools/j1939_84/bus/j1939/J1939Test.java, src-test/org/etools/j1939_84/controllers/TableA1ValidatorTest.java, src-test/org/etools/j1939_84/controllers/part1/BroadcastValidatorTest.java, src-test/org/etools/j1939_84/controllers/part1/Part01Step26ControllerTest.java, src-test/org/etools/j1939_84/model/OBDModuleInformationTest.java, src/org/etools/j1939_84/controllers/TableA1Validator.java, src/org/etools/j1939_84/controllers/part1/BroadcastValidator.java, src/org/etools/j1939_84/controllers/part1/Part01Step26Controller.java, src/org/etools/j1939_84/model/OBDModuleInformation.java
In the `OBDModuleInformation` I added a list of SPNs which will be filtered out of the data stream SPNs for that module.  This list starts with Eric's provided numbers. 
In the `TableA1Validator` as the expected messages are being reported, the list of SPNs supported by the module, but omitted is written to the log.  In additions, as the other SPNs are being processed to find the PGNs they are in, if additional SPs are found to be in multiple PGs, they will be added to the `omittedSPNsList` in the `OBDModuleInformation` and will be omitted in future runs.  Additionally, their omission is noted in the log.
=> Fix #510 Part 1 Step 26 - Exclude checking for particular SPNs

src-test/org/etools/j1939_84/modules/VehicleInformationModuleTest.java, src-test/org/etools/j1939_84/ui/UserInterfacePresenterTest.java, src-test/org/etools/j1939_84/ui/VehicleInformationDialogTest.java, src-test/org/etools/j1939_84/ui/VehicleInformationPresenterTest.java, src/org/etools/j1939_84/modules/VehicleInformationModule.java, src/org/etools/j1939_84/ui/UserInterfacePresenter.java, src/org/etools/j1939_84/ui/VehicleInformationContract.java, src/org/etools/j1939_84/ui/VehicleInformationDialog.java, src/org/etools/j1939_84/ui/VehicleInformationPresenter.java
Rather than ignoring the exceptions from reading the vehicle, write them to the logger.
=> Fix #538 Log when Vehicle Information can't be gathered

src-test/org/etools/j1939_84/bus/j1939/J1939Test.java, src-test/org/etools/j1939_84/modules/DiagnosticMessageModuleTest.java, src-test/org/etools/j1939_84/modules/DiagnosticReadinessModuleTest.java, src-test/org/etools/j1939_84/modules/VehicleInformationModuleTest.java, src/org/etools/j1939_84/bus/Packet.java, src/org/etools/j1939_84/bus/j1939/J1939.java, src/org/etools/j1939_84/bus/j1939/J1939TP.java
1250 ms should be used as the timeout with Global Requests
200 ms should be used for DS requests
=> Fix #540 - Use different timeout with global requests and log the time we waited in the report

src-test/org/etools/j1939_84/controllers/part01/Part01Step13ControllerTest.java, src-test/org/etools/j1939_84/controllers/part02/Part02Step02ControllerTest.java, src/org/etools/j1939_84/controllers/part01/Part01Step13Controller.java, src/org/etools/j1939_84/controllers/part02/Part02Step02Controller.java
If the active count == 0xFF, then only it should be ignored, not the entire packet.
=> Fix #553 DM5 Active and Previously Active values are being improperly filtered

src-test/org/etools/j1939_84/controllers/part01/Part01Step05ControllerTest.java, src/org/etools/j1939_84/controllers/part01/Part01Step05Controller.java
The `vinDecoder.getModelYear()` method shortcuts if the VIN is invalid.  Thus the tool is erroneously reporting a mismatch in the model year if the VIN is invalid.
This switches the order of the processing to not report a mis-matched model year if the VIN is invalid.
=> Fix #564 Part 1 Step 5: Invalid VINs should not cause other failures
