battjt/j1939-84

src-test/org/etools/j1939_84/controllers/part1/Step09ControllerTest.java
src-test/org/etools/j1939_84/utils/AbstractControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step03Controller.java
src/org/etools/j1939_84/controllers/part1/Step09Controller.java

Mark a bug and update the AbstractTestClass to be able to mock out OBD modules.

Put FIXME step 09 controller as I found a bug and don't want to loose it.

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM2PreviouslyActiveDTCTest.java
src/org/etools/j1939_84/bus/j1939/packets/DM2PreviouslyActiveDTC.java
src/org/etools/j1939_84/modules/DTCModule.java

Add DM2 packets and the update to DTCModule to retrieve them.

Add dm2 packet object

---

src-test/org/etools/j1939_84/controllers/part1/Step06ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step06Controller.java

Fix null pointer on check for family name char.

Fix #43 Update the Part 1 Step 6 to fix null pointer bug.

---

etc/J1939_84.launch
src-test/org/etools/j1939_84/bus/MultiQueueTest.java
src-test/org/etools/j1939_84/bus/RP1210BusTest.java
src-test/org/etools/j1939_84/bus/RP1210Test.java
src-test/org/etools/j1939_84/bus/j1939/J1939TPTest.java
src-test/org/etools/j1939_84/bus/j1939/J1939Test.java
src/org/etools/j1939_84/J1939_84.java
src/org/etools/j1939_84/bus/Bus.java
src/org/etools/j1939_84/bus/EchoBus.java
src/org/etools/j1939_84/bus/MultiQueue.java
src/org/etools/j1939_84/bus/RP1210.java
src/org/etools/j1939_84/bus/RP1210Bus.java
src/org/etools/j1939_84/bus/j1939/J1939TP.java

No significant bugs fixed.  Tests were fixed and the interface was cleaned up a bit in places.

Fix j1939 tests

---

src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java

removed step 10 and step 11 as they are not yet completed

Correct Part01Controller to only run controllers that exist

---

src-test/org/etools/j1939_84/bus/j1939/packets/ParsedPacketTest.java
src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step11ControllerTest.java
src/org/etools/j1939_84/bus/j1939/packets/ParsedPacket.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Step11Controller.java
src/org/etools/j1939_84/modules/DiagnosticReadinessModule.java
src/org/etools/j1939_84/resources/version.properties

Testing still needs to be added.

Fix #16 & Fix #68. 

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM25ExpandedFreezeFrameTest.java
src/org/etools/j1939_84/bus/j1939/packets/DM25ExpandedFreezeFrame.java
src/org/etools/j1939_84/bus/j1939/packets/FreezeFrame.java

Fix #79 Adding DM25ExpandedFreezeFrame message handling to the project.

Dm25 expanded freeze frame

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM31ScaledTestResultTest.java
src/org/etools/j1939_84/bus/j1939/packets/DM31ScaledTestResults.java

Add toString method to DM31 messaging.

Add toString() override method to DM31 and the associated testing.

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM31ScaledTestResultTest.java
src-test/org/etools/j1939_84/controllers/part1/Step03ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step04ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step11ControllerTest.java
src-test/org/etools/j1939_84/modules/DTCModuleTest.java
src/org/etools/j1939_84/bus/j1939/packets/DM31ScaledTestResults.java
src/org/etools/j1939_84/controllers/StepController.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Step01Controller.java
src/org/etools/j1939_84/controllers/part1/Step02Controller.java
src/org/etools/j1939_84/controllers/part1/Step03Controller.java
src/org/etools/j1939_84/controllers/part1/Step04Controller.java
src/org/etools/j1939_84/controllers/part1/Step05Controller.java
src/org/etools/j1939_84/controllers/part1/Step06Controller.java
src/org/etools/j1939_84/controllers/part1/Step07Controller.java
src/org/etools/j1939_84/controllers/part1/Step08Controller.java
src/org/etools/j1939_84/controllers/part1/Step09Controller.java
src/org/etools/j1939_84/controllers/part1/Step10Controller.java
src/org/etools/j1939_84/controllers/part1/Step11Controller.java
src/org/etools/j1939_84/controllers/part1/Step12Controller.java
src/org/etools/j1939_84/controllers/part1/Step16Controller.java
src/org/etools/j1939_84/modules/DTCModule.java
src/org/etools/j1939_84/modules/DiagnosticReadinessModule.java

Variety of changes to update the how steps are run.  Fix in some modules to move the reporting into the controllers.

Update to report step correctly

---

src/org/etools/j1939_84/bus/j1939/packets/DM33EmissionIncreasingAuxiliaryEmissionControlDeviceActiveTime.java

Add dm33s to the code base.

---

src/org/etools/j1939_84/bus/j1939/J1939.java
src/org/etools/j1939_84/bus/j1939/packets/DM28PermanentEmissionDTCPacket.java
src/org/etools/j1939_84/bus/simulated/Engine.java
src/org/etools/j1939_84/controllers/Controller.java
src/org/etools/j1939_84/modules/DTCModule.java
src/org/etools/j1939_84/modules/VehicleInformationModule.java

Various bug fixes and building out of simulated engine stuff and reporting to the UI tool

Various bug fixes and corrections

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM28PermanentEmissionDTCPacketTest.java

add to DM28 testing

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM33EmissionIncreasingAuxiliaryEmissionControlDeviceActiveTimeTest.java
src/org/etools/j1939_84/bus/j1939/packets/DM33EmissionIncreasingAuxiliaryEmissionControlDeviceActiveTime.java
src/org/etools/j1939_84/bus/j1939/packets/EngineHoursTimer.java
src/org/etools/j1939_84/bus/j1939/packets/LampStatus.java

Update EngineHoursTimer to correctly pull bytes off the packet, update LampStatus to capitalize correctly, and add DM33 message handling and associated unit tests to code base.  #102

Adding DM33 message handling and associated testing to the code base.

---

src-test/org/etools/j1939_84/modules/DTCModuleTest.java
src/org/etools/j1939_84/bus/j1939/J1939.java
src/org/etools/j1939_84/model/RequestResult.java
src/org/etools/j1939_84/modules/DTCModule.java

Fix#111 Update DTCModule/DTCModuleTest to handle DM`11 messaging correctly

Update DTCModule/DTCModuleTest to handle DM`11 messaging

---

src-test/org/etools/j1939_84/modules/DTCModuleTest.java
src/org/etools/j1939_84/modules/DTCModule.java

Fix #90 Add DM33 testing to the DTCModuleTest file.

DTCModule/DTCModuleTest updates for DM33 message handling.

---

src-test/org/etools/j1939_84/modules/DTCModuleTest.java
src/org/etools/j1939_84/modules/DTCModule.java

DM28 updates to DTCModule/DTCModuleTest

---

src/org/etools/j1939_84/controllers/part1/Step10Controller.java

Fix the build

---

src-test/org/etools/j1939_84/modules/DTCModuleTest.java
src/org/etools/j1939_84/modules/DTCModule.java

Update DTCModule/DTCModuleTest with message handling per requirements for DM6 all associated testing.

Add DM6 message handling to the DTCModule

---

src-test/org/etools/j1939_84/controllers/part1/Step10ControllerTest.java
src-test/org/etools/j1939_84/modules/DTCModuleTest.java
src/org/etools/j1939_84/controllers/part1/Step10Controller.java
src/org/etools/j1939_84/modules/DTCModule.java

Fix #68 Add testing for the DM21 stuff and more code clean up.

Update DTCModule/DTCModuleTest for DM21

---

src-test/org/etools/j1939_84/modules/DTCModuleTest.java

Fix #84 add testing to DM31 messaging.

Update DTCModuleTest for DM31

---

src-test/org/etools/j1939_84/modules/DTCModuleTest.java
src/org/etools/j1939_84/modules/DTCModule.java

Fix #125 add DM26 message handling and associated tests to the DTCModule/DTCModuleTest

Update DTCModule/DTCModuleTest for DM26 messaging

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM31ScaledTestResultTest.java
src-test/org/etools/j1939_84/bus/j1939/packets/DiagnosticTroubleCodePacketTest.java
src-test/org/etools/j1939_84/bus/j1939/packets/LampStatusTest.java
src-test/org/etools/j1939_84/controllers/part1/SectionA5VerifierTest.java
src-test/org/etools/j1939_84/model/RequestResultTest.java
src/org/etools/j1939_84/controllers/part1/SectionA5Verifier.java

#128 Adding Section A.5 verification to code base and fix tests.

Add Section A.5 verification steps

---

src-test/org/etools/j1939_84/controllers/part1/SectionA5VerifierTest.java
src/org/etools/j1939_84/controllers/part1/SectionA5Verifier.java

#128 Adding Section A.5 verification to code base and fix tests.

Adding Section A.5 verification 

---

src-test/org/etools/j1939_84/controllers/part1/Step10ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step10Controller.java

Fix#15 Updating step 10 to use the SectionA5Verifier to validate.

Adding Step10Controller updates to use SectionA5Verifier

---

src/org/etools/j1939_84/controllers/part1/Step09Controller.java

Fix #14 Update the test to verify added features of step number, etc.

Remove FIXME entered into file

---

src-test/org/etools/j1939_84/bus/j1939/packets/MonitoredSystemTest.java
src-test/org/etools/j1939_84/controllers/part1/TableA6ValidatorTest.java
src-test/org/etools/j1939_84/modules/DTCModuleTest.java
src/org/etools/j1939_84/bus/j1939/packets/CompositeSystem.java
src/org/etools/j1939_84/bus/j1939/packets/MonitoredSystem.java
src/org/etools/j1939_84/controllers/part1/DataRepository.java
src/org/etools/j1939_84/controllers/part1/SectionA5Verifier.java
src/org/etools/j1939_84/controllers/part1/TableA6Validator.java
src/org/etools/j1939_84/modules/DiagnosticReadinessModule.java

Add functionality associated with adding Table A.6.1 and Table A.6.2 (Fix #137) and clean up code.

Table a6 validator

---

src-test/org/etools/j1939_84/model/OBDModuleInformationTest.java
src-test/org/etools/j1939_84/model/VehicleInformationTest.java
src/org/etools/j1939_84/controllers/part1/DataRepository.java
src/org/etools/j1939_84/model/OBDModuleInformation.java
src/org/etools/j1939_84/model/VehicleInformation.java

Fix #140 Update dataRepository to return copies of objects so things aren't getting changed in areas that we do not want.

Update dataRepository to return copies of objects.

---

src-test/org/etools/j1939_84/controllers/part1/Step10ControllerTest.java

Fix #15 Update the test to complete the testing.

Update the step 10 test to complete

---

src-test/org/etools/j1939_84/controllers/part1/Step12ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step12Controller.java

Fix #75 add Step12 controller to the code base and its associated unit tests.

Add Step12 controller to the code base and its associated tests

---

src/org/etools/j1939_84/model/VehicleInformation.java
src/org/etools/j1939_84/modules/ReportFileModule.java

Fix #140 fix the null pointer introduced when writing the clone() method of these objects.

Fix null pointer bug in ReportModule

---

src/org/etools/j1939_84/modules/ReportFileModule.java

#146b - fix the reporting to show up in all part of the report.  Test still need to be updated.

Update ReportFileModule to correctly handle reporting throughout the vehicle report consistantly

---

src-test/org/etools/j1939_84/controllers/part1/Step09ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step09Controller.java

#146 - fix the reporting to show up in all part of the report.  Step09Controller & Step09ControllerTest updated to robust reporting.  Additionally, logic was corrected for requirements.

Correctly report up the progress of the individual tests as completed with a pass/fail

---

src-test/org/etools/j1939_84/controllers/part1/SectionA6ValidatorTest.java
src-test/org/etools/j1939_84/controllers/part1/TableA6ValidatorTest.java
src/org/etools/j1939_84/controllers/Validator.java
src/org/etools/j1939_84/controllers/part1/SectionA6Validator.java
src/org/etools/j1939_84/controllers/part1/TableA6Validator.java

#146 - fix the reporting to show up in all part of the report.  SectionA6Validator, SectionA6ValidatorTest, TableA6Validator and TableA6ValidatorTest updated to robust reporting.

Update the Validators to report out using the correct pass/fail 

---

src-test/org/etools/j1939_84/controllers/part1/Step07ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step07Controller.java

#146 - fix the reporting to show up in all part of the report.  Step07Controller & Step07ControllerTest updated to robust reporting.

Update the logging to report in the correct pass/fail format

---

src-test/org/etools/j1939_84/controllers/part1/Step12ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step12Controller.java
src/org/etools/j1939_84/controllers/part1/TableA7Validator.java

#146 - fix the reporting to show up in all part of the report.  Step12Controller, Step012ControllerTest & TableA7Validator updated to robust reporting.

Update Step12 to report out pass/fail per new message reporting structure

---

src-test/org/etools/j1939_84/controllers/part1/TableA7ValidatorTest.java
src-test/org/etools/j1939_84/modules/DateTimeModuleTest.java
src/org/etools/j1939_84/controllers/Controller.java
src/org/etools/j1939_84/controllers/StepController.java
src/org/etools/j1939_84/controllers/part1/Step01Controller.java
src/org/etools/j1939_84/controllers/part1/Step02Controller.java
src/org/etools/j1939_84/controllers/part1/Step03Controller.java
src/org/etools/j1939_84/controllers/part1/Step04Controller.java
src/org/etools/j1939_84/controllers/part1/Step05Controller.java
src/org/etools/j1939_84/controllers/part1/Step06Controller.java
src/org/etools/j1939_84/controllers/part1/Step07Controller.java
src/org/etools/j1939_84/controllers/part1/Step08Controller.java
src/org/etools/j1939_84/controllers/part1/Step09Controller.java
src/org/etools/j1939_84/controllers/part1/Step10Controller.java
src/org/etools/j1939_84/controllers/part1/Step11Controller.java
src/org/etools/j1939_84/controllers/part1/Step12Controller.java

Fix #161 Update the StepController to handle the part number, step number and the total number of steps.

Extract part number, step number & total # steps up to the StepController

---

src/org/etools/j1939_84/controllers/part1/Step16Controller.java

#146 - fix the reporting to show up in all part of the report.  Step16Controller to build with new reporting structure.  Partial check in to fix build issue only.  Logic and reporting still need to be updated for this step.

Fix build Step16 needs to be updated to fix new reporting configuration

---

src-test/org/etools/j1939_84/controllers/part1/Step04ControllerTest.java
src-test/org/etools/j1939_84/utils/AbstractControllerTest.java
src/org/etools/j1939_84/bus/j1939/J1939.java
src/org/etools/j1939_84/controllers/part1/Step04Controller.java
src/org/etools/j1939_84/modules/OBDTestsModule.java

Fix #160.  Update Step04 to report based on the new methodology.  Correct the reporting out to the modules per Eric's requests.  Fix logic errors, etc.

Merge Step04 Updates

---

src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step13ControllerTest.java
src/org/etools/j1939_84/bus/j1939/packets/CompositeSystem.java
src/org/etools/j1939_84/controllers/StepController.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Step13Controller.java
src/org/etools/j1939_84/modules/DiagnosticReadinessModule.java

Fix #18 - Add Step13 logic as written in the requirements to the cod base and its associated testing.

Merge Step13 into code base

---

src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step14ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Step03Controller.java
src/org/etools/j1939_84/controllers/part1/Step14Controller.java
src/org/etools/j1939_84/model/OBDModuleInformation.java
src/org/etools/j1939_84/modules/DiagnosticReadinessModule.java

Fix #19 - Add Step14 and associated changes needed to implement.  Include unit tests updates to Part01Controller and Step14.  Additionally testing will be added for module changes under it own ticket.

Add Step14 to project

---

src-test/org/etools/j1939_84/controllers/part1/Step14ControllerTest.java
src-test/org/etools/j1939_84/utils/VinGenerator.java
src/org/etools/j1939_84/modules/SummaryModule.java

Fix #201 Remove miscellaneous System.out.println()s from various files.

House keeping for System.out.println()s.

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM1ActiveDTCsPacketTest.java
src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step15ControllerTest.java
src-test/org/etools/j1939_84/modules/DTCModuleTest.java
src/org/etools/j1939_84/bus/j1939/J1939.java
src/org/etools/j1939_84/bus/simulated/Engine.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Step15Controller.java
src/org/etools/j1939_84/modules/DTCModule.java

Fix #20 - Add Step15 and associated changes needed to implement.  Also included were updates for the implementation of Step15 to the following classes and their respective unit test classes: Part01Controller, J1939, DTCModule, DM1ActiveDTCsPacketTest & Engine.

Add Step15Controller to the project

---

src-test/org/etools/j1939_84/bus/j1939/packets/SupportedSPNTest.java
src-test/org/etools/j1939_84/controllers/part1/Step04ControllerTest.java
src-test/org/etools/j1939_84/modules/DiagnosticReadinessModuleTest.java
src/org/etools/j1939_84/controllers/part1/Step14Controller.java

Fix #201 Remove miscellaneous System.out.println()s from various files, add FIXME's for items needing address in work already captured in tickets and clean up various other things.

Clean up code

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM1ActiveDTCsPacketTest.java
src-test/org/etools/j1939_84/bus/j1939/packets/DM25ExpandedFreezeFrameTest.java
src-test/org/etools/j1939_84/bus/j1939/packets/DM28PermanentEmissionDTCPacketTest.java
src-test/org/etools/j1939_84/bus/j1939/packets/DM31ScaledTestResultTest.java
src-test/org/etools/j1939_84/bus/j1939/packets/DM6PendingEmissionDTCPacketTest.java
src-test/org/etools/j1939_84/bus/j1939/packets/DTCLampStatusTest.java
src-test/org/etools/j1939_84/bus/j1939/packets/DiagnosticTroubleCodePacketTest.java
src-test/org/etools/j1939_84/bus/j1939/packets/DiagnosticTroubleCodeTest.java
src-test/org/etools/j1939_84/modules/DTCModuleTest.java
src/org/etools/j1939_84/bus/j1939/packets/DiagnosticTroubleCode.java

Fix #204 - updated DTC formatting and corrected all testing using DTCs.

Update the format of DTCs per feedback from client

---

src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step17ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Step17Controller.java

Fix #22 Add Step17Controller and its associated unit testing to the project.

Add Step17 to the project

---

src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step18ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Step18Controller.java

Fix #23 add Step18Controller to Part01 of the project along with its associated unit tests.

Add Step18Controller and Step18ControllerTest to the project

---

src-test/org/etools/j1939_84/controllers/part1/Step09ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step09Controller.java

Fix #175 Update logging to remove the recording of passes.

StepController09Update

---

src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java

Fix #23 add Step18Controller to Part01 of the project along with its associated unit tests.

Correction to test

---

src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/SectionA5VerifierTest.java
src-test/org/etools/j1939_84/controllers/part1/Step10ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step20ControllerTest.java
src-test/org/etools/j1939_84/modules/DTCModuleTest.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/SectionA5Verifier.java
src/org/etools/j1939_84/controllers/part1/Step10Controller.java
src/org/etools/j1939_84/controllers/part1/Step20Controller.java
src/org/etools/j1939_84/modules/DTCModule.java

Fix #25 Add Step20Controller and its associated unit tests to the project.  Also include are updates to the new BusResult return for a requestDM28.

Add Step20Controller

---

src-test/org/etools/j1939_84/controllers/part1/SectionA5VerifierTest.java
src/org/etools/j1939_84/controllers/part1/SectionA5Verifier.java

Fix #217 Update SectionA5Verifier to be able to independently call various steps to allow for needed configurability.

Update SectionA5Verifier to be more configurable

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM27AllPendingDTCsPacketTest.java
src/org/etools/j1939_84/bus/j1939/packets/DM27AllPendingDTCsPacket.java

Fix #226 Adding DM27 messaging and its associated unit test to the project.

Adding DM27 messaging and unit tests

---

src/org/etools/j1939_84/bus/simulated/Engine.java

Update Engine with a real copy of a DM27 message we received from a truck.

Use a copy of a real DM27 message in simulator

---

src-test/org/etools/j1939_84/controllers/part1/Step10ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step10Controller.java

Fix #203 & Fix #223.  Per feedback from Eric we needed to remove the pre/post verification os the Section A5 table as it doesn't make sense to do that verification here because the current state of the engine.

Update Step 10 per feedback from clients

---

src-test/org/etools/j1939_84/controllers/part1/Step07ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step07Controller.java

Fix #234 remove all pass logging for the Step07Controller and Step07ControllerTest.

Remove pass logging in Step 7

---

src-test/org/etools/j1939_84/bus/j1939/packets/SlotTest.java
src/org/etools/j1939_84/bus/j1939/packets/Slot.java

This enhances Slot to allow it to produce a decimal value, detect NotAvailable and Error in the values and print the value with the units of measure.

Fix #238 - Enhance Slot to produce values for all possible types

---

src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step22ControllerTest.java
src/org/etools/j1939_84/bus/j1939/packets/DM29DtcCounts.java
src/org/etools/j1939_84/bus/simulated/Engine.java
src/org/etools/j1939_84/bus/simulated/Sim.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Step22Controller.java
src/org/etools/j1939_84/modules/DTCModule.java

Add Part01 Step22 Controller and its associated testing to the project.

Add Part01 Step22

---

j1939-84.iml
src-test/org/etools/j1939_84/bus/j1939/packets/DM31DtcToLampAssociationTest.java
src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step23ControllerTest.java
src/org/etools/j1939_84/bus/simulated/Engine.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Step23Controller.java
src/org/etools/j1939_84/modules/DiagnosticReadinessModule.java

Fix #28 Add Part01 Step 23 to the project along with its unit testing and updates to the simulated engine and the module handling the messages.

Add Part01 Step 23

---

src-test/org/etools/j1939_84/controllers/part1/Step23ControllerTest.java

Fix #28 Add Part01 Step 23 to the project along with its unit testing and updates to the simulated engine and the module handling the messages.

Fix #28 Add Part01 Step 23

---

.idea/codeStyles/Project.xml
src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step24ControllerTest.java
src/org/etools/j1939_84/bus/simulated/Engine.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Step24Controller.java
src/org/etools/j1939_84/modules/DiagnosticReadinessModule.java

Fix #29 Add Part01 Step 24 to the project along with its unit testing and updates to the simulated engine and the module handling the messages.

Add Part01 Step24

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM25ExpandedFreezeFrameTest.java
src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step25ControllerTest.java
src-test/org/etools/j1939_84/utils/CollectionUtilsTest.java
src/org/etools/j1939_84/bus/j1939/packets/DM20MonitorPerformanceRatioPacket.java
src/org/etools/j1939_84/bus/simulated/Engine.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Step25Controller.java
src/org/etools/j1939_84/model/OBDModuleInformation.java
src/org/etools/j1939_84/modules/DTCModule.java
src/org/etools/j1939_84/utils/CollectionUtils.java

Fix #30 Add Part01 Step 25 to the project along with its unit testingIn addition, updates to the simulated engine and the module handling the messages were included.

Add Step25 to the project

---

src-test/org/etools/j1939_84/controllers/part1/Step14ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step14Controller.java

Clean up code, remove unnecessary pass logging, etc.

Basic clean up

---

src-test/org/etools/j1939_84/bus/RP1210BusTest.java
src-test/org/etools/j1939_84/bus/RP1210Test.java
src-test/org/etools/j1939_84/controllers/part1/Part01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Step06ControllerTest.java
src/org/etools/j1939_84/bus/RP1210Bus.java
src/org/etools/j1939_84/bus/j1939/J1939.java

Simple test fixes for NL != \n
Fix catching echo packet when sending packet with address that is different than the adapter.
Fix rp1210bus tests
BIG: fix pgn destination address decoding

rp1210 fixes

---

src-test/org/etools/j1939_84/bus/EchoBusTest.java
src-test/org/etools/j1939_84/bus/EchoTest.java
src-test/org/etools/j1939_84/bus/PacketTest.java
src-test/org/etools/j1939_84/bus/j1939/J1939TPTest.java
src-test/org/etools/j1939_84/bus/j1939/J1939Test.java
src-test/org/etools/j1939_84/bus/j1939/packets/DTCLampStatusTest.java
src-test/org/etools/j1939_84/bus/j1939/packets/DiagnosticTroubleCodeTest.java
src-test/org/etools/j1939_84/bus/j1939/packets/ParsedPacketTest.java
src-test/org/etools/j1939_84/controllers/TestResultsListener.java
src/org/etools/j1939_84/bus/Packet.java
src/org/etools/j1939_84/bus/RP1210Bus.java
src/org/etools/j1939_84/bus/j1939/J1939TP.java
src/org/etools/j1939_84/bus/j1939/packets/ParsedPacket.java
src/org/etools/j1939_84/bus/simulated/Engine.java
src/org/etools/j1939_84/bus/simulated/GenerateSimFile.java
src/org/etools/j1939_84/controllers/TableA1Validator.java
src/org/etools/j1939_84/controllers/part1/BroadcastValidator.java
src/org/etools/j1939_84/controllers/part1/Step26Controller.java
src/org/etools/j1939_84/model/RequestResult.java

Fix Packet.getId()
Fix J1939BusTest
various other tiny fixes.
Format wars with Matt.

Test warning cleanup

---

src-test/org/etools/j1939_84/controllers/part1/Step22ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Step22Controller.java

Fix #429 Update the packet to use built in methods and fix logic for missing check per client feedback

Fix logic of Step 22 per client feedback.

---

src-test/org/etools/j1939_84/controllers/part2/Part02ControllerTest.java
src-test/org/etools/j1939_84/controllers/part2/Step02ControllerTest.java
src/org/etools/j1939_84/controllers/OverallController.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part2/Part02Controller.java
src/org/etools/j1939_84/controllers/part2/Step02Controller.java

Fix #253 Add Part02/Step02 to the project.  Updated the project to pass the DataRepository to the individual parts to allow for data carry over from one part of the test to the next.

Add Part02/Step02 to the project

---

src-test/org/etools/j1939_84/controllers/part2/Part02Step05ControllerTest.java
src/org/etools/j1939_84/controllers/part2/Part02Step05Controller.java

Fix #256 Add Part02Step05Controller to the project and it associated unit testing.

Add Part02- Step05 to the project

---

src-test/org/etools/j1939_84/bus/j1939/packets/DM29DtcCountsTest.java
src/org/etools/j1939_84/bus/j1939/packets/DM29DtcCounts.java

Update the toString() of the packet to parse the values to detect Not Available and Error.

Fix #474 - Part 1 Step 22 Not Available should be reported as such

---

src-test/org/etools/j1939_84/bus/j1939/J1939Test.java
src-test/org/etools/j1939_84/bus/j1939/packets/ComponentIdentificationPacketTest.java
src-test/org/etools/j1939_84/controllers/part1/Part01Step09ControllerTest.java
src-test/org/etools/j1939_84/controllers/part2/Part02Step07ControllerTest.java
src/org/etools/j1939_84/controllers/part1/Part01Step09Controller.java
src/org/etools/j1939_84/controllers/part2/Part02Step07Controller.java

Fix #258 and updates to accommodate #461 updates to the part 01 step 09 to save the ComponentIdentification for comparison in part 02 step 07.

Add Part02 Step 07 to the project

---

src-test/org/etools/j1939_84/controllers/part1/BroadcastValidatorTest.java
src-test/org/etools/j1939_84/controllers/part1/BusServiceTest.java
src-test/org/etools/j1939_84/controllers/part1/Part01Step26ControllerTest.java
src-test/org/etools/j1939_84/controllers/part2/Part02Step15ControllerTest.java
src-test/org/etools/j1939_84/controllers/part2/Part02Step16ControllerTest.java
src-test/org/etools/j1939_84/utils/AbstractControllerTest.java
src/org/etools/j1939_84/controllers/BroadcastValidator.java
src/org/etools/j1939_84/controllers/BusService.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Part01Step26Controller.java
src/org/etools/j1939_84/controllers/part2/Part02Controller.java
src/org/etools/j1939_84/controllers/part2/Part02Step17Controller.java

There are no unit tests for Part 2 Step 17 because I'm waiting to finish writing the tests for Part 1 Step 26 from which this step is derived.  The tests are for Part 1 Step 26 are waiting on final approval from the client (as it's a PITA to keep changing them)

Fix #268 - Implement Part 2 Step 17

---

src-test/org/etools/j1939_84/controllers/part1/Part01Step01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part1/Part01Step27ControllerTest.java
src-test/org/etools/j1939_84/controllers/part2/Part02Step01ControllerTest.java
src-test/org/etools/j1939_84/controllers/part2/Part02Step18ControllerTest.java
src/org/etools/j1939_84/controllers/StepController.java
src/org/etools/j1939_84/controllers/part1/Part01Controller.java
src/org/etools/j1939_84/controllers/part1/Part01Step01Controller.java
src/org/etools/j1939_84/controllers/part1/Part01Step10Controller.java
src/org/etools/j1939_84/controllers/part1/Part01Step27Controller.java
src/org/etools/j1939_84/controllers/part2/Part02Step01Controller.java
src/org/etools/j1939_84/controllers/part2/Part02Step18Controller.java

Fix #269 and fix various bugs associated with the user interface buttons and closing behaviors.  Also, up steps with comments to reference other step which are similar.  Clean up code and update to new API design.

Add Part 02 Step 18 and fix bugs

---

src/org/etools/j1939_84/J1939_84.java
src/org/etools/j1939_84/controllers/part01/Part01Step01Controller.java
src/org/etools/j1939_84/controllers/part01/Part01Step27Controller.java
src/org/etools/j1939_84/controllers/part02/Part02Step01Controller.java
src/org/etools/j1939_84/controllers/part02/Part02Step18Controller.java

Separate the testing args so they can be used correctly.

Questions were not showing
